/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package models.views;

/**
 *
 * @author Markus
 */
public class CityInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CityInfoPanel
     */
    public CityInfoPanel() {
        initComponents();
    }
    
    public void setCityName(String cityName) {
        l_kota.setText(cityName);
    }

    public void setCityDistance(String distance){
        l_jarak.setText(distance);
    }

    public void setCityElevation(String elevation){
        l_eleveasi.setText(elevation);
    }
    
    public String getCityDistanceLabel() {
        return l_jarak.getText();
    }
    
    public String getCityElevationLabel() {
        return l_eleveasi.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new models.views.RoundedPanel();
        l_kota = new javax.swing.JLabel();
        l_jarak = new javax.swing.JLabel();
        l_eleveasi = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        roundedPanel1.setBackground(new java.awt.Color(51, 51, 51));
        roundedPanel1.setRoundBottomLeft(30);
        roundedPanel1.setRoundBottomRight(30);

        l_kota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l_kota.setForeground(new java.awt.Color(255, 255, 255));
        l_kota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_kota.setText("KOTA");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_kota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_kota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        l_jarak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_jarak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_jarak.setText("Jarak: ");

        l_eleveasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_eleveasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_eleveasi.setText("Elevasi: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(l_jarak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(l_eleveasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_jarak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_eleveasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l_eleveasi;
    private javax.swing.JLabel l_jarak;
    private javax.swing.JLabel l_kota;
    private models.views.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
