package gui;

import utils.ComponentUtils;
import utils.UColors;

import javax.swing.*;

/**
 * Kelas GUI yang digunakan untuk menampilkan peta serta pilihan kota tujuan.
 * Interaksi pada kelas ini akan mengisi kota tujuan pada frame utama.
 *
 * @author <a href="https://github.com/vianneynara">Nara</a>
 * */

public class SelectDestinationDialog extends javax.swing.JDialog {
    private MainFrame mainFrame;

    /**
     * Creates new form SelectOriginDialog
     */
    public SelectDestinationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = (MainFrame) parent;

        // Mengatur warna UI
        ComponentUtils.setBackgroundColor(UColors.MAROON.toColor(), this.getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAYERED_PANE = new javax.swing.JLayeredPane();
        PETA_UTAMA = new javax.swing.JLabel();
        b_brebes = new javax.swing.JButton();
        b_tegal = new javax.swing.JButton();
        b_cilacap = new javax.swing.JButton();
        b_banyumas = new javax.swing.JButton();
        b_purbalingga = new javax.swing.JButton();
        b_pemalang = new javax.swing.JButton();
        b_pekalongan = new javax.swing.JButton();
        b_kebumen = new javax.swing.JButton();
        b_purworejo = new javax.swing.JButton();
        b_banjarnegara = new javax.swing.JButton();
        b_kendal = new javax.swing.JButton();
        b_batang = new javax.swing.JButton();
        b_wonosobo = new javax.swing.JButton();
        b_temanggung = new javax.swing.JButton();
        b_magelang = new javax.swing.JButton();
        b_semarang = new javax.swing.JButton();
        b_demak = new javax.swing.JButton();
        b_boyolali = new javax.swing.JButton();
        b_klaten = new javax.swing.JButton();
        b_kudus = new javax.swing.JButton();
        b_jepara = new javax.swing.JButton();
        b_rembang = new javax.swing.JButton();
        b_pati = new javax.swing.JButton();
        b_blora = new javax.swing.JButton();
        b_grobogan = new javax.swing.JButton();
        b_sragen = new javax.swing.JButton();
        b_sukoharjo = new javax.swing.JButton();
        b_karanganyar = new javax.swing.JButton();
        b_wonogiri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select The Origin");
        setUndecorated(true);

        PETA_UTAMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/peta_jawa_tengah.jpg"))); // NOI18N

        b_brebes.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_brebes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_brebes.setText("Brebes");
        b_brebes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_brebesActionPerformed(evt);
            }
        });

        b_tegal.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_tegal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_tegal.setText("Tegal");
        b_tegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tegalActionPerformed(evt);
            }
        });

        b_cilacap.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_cilacap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_cilacap.setText("Cilacap");
        b_cilacap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cilacapActionPerformed(evt);
            }
        });

        b_banyumas.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_banyumas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_banyumas.setText("Banyumas");
        b_banyumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_banyumasActionPerformed(evt);
            }
        });

        b_purbalingga.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_purbalingga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_purbalingga.setText("Purbalingga");
        b_purbalingga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_purbalinggaActionPerformed(evt);
            }
        });

        b_pemalang.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_pemalang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_pemalang.setText("Pemalang");
        b_pemalang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pemalangActionPerformed(evt);
            }
        });

        b_pekalongan.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_pekalongan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_pekalongan.setText("Pekalongan");
        b_pekalongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pekalonganActionPerformed(evt);
            }
        });

        b_kebumen.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_kebumen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_kebumen.setText("Kebumen");
        b_kebumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kebumenActionPerformed(evt);
            }
        });

        b_purworejo.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_purworejo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_purworejo.setText("Purworejo");
        b_purworejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_purworejoActionPerformed(evt);
            }
        });

        b_banjarnegara.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_banjarnegara.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_banjarnegara.setText("Banjarnegara");
        b_banjarnegara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_banjarnegaraActionPerformed(evt);
            }
        });

        b_kendal.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_kendal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_kendal.setText("Kendal");
        b_kendal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kendalActionPerformed(evt);
            }
        });

        b_batang.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_batang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_batang.setText("Batang");
        b_batang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_batangActionPerformed(evt);
            }
        });

        b_wonosobo.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_wonosobo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_wonosobo.setText("Wonosobo");
        b_wonosobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_wonosoboActionPerformed(evt);
            }
        });

        b_temanggung.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_temanggung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_temanggung.setText("Temanggung");
        b_temanggung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_temanggungActionPerformed(evt);
            }
        });

        b_magelang.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_magelang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_magelang.setText("Magelang");
        b_magelang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_magelangActionPerformed(evt);
            }
        });

        b_semarang.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_semarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_semarang.setText("Semarang");
        b_semarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_semarangActionPerformed(evt);
            }
        });

        b_demak.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_demak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_demak.setText("Demak");
        b_demak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_demakActionPerformed(evt);
            }
        });

        b_boyolali.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_boyolali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_boyolali.setText("Boyolali");
        b_boyolali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boyolaliActionPerformed(evt);
            }
        });

        b_klaten.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_klaten.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_klaten.setText("Klaten");
        b_klaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_klatenActionPerformed(evt);
            }
        });

        b_kudus.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_kudus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_kudus.setText("Kudus");
        b_kudus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kudusActionPerformed(evt);
            }
        });

        b_jepara.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_jepara.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_jepara.setText("Jepara");
        b_jepara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_jeparaActionPerformed(evt);
            }
        });

        b_rembang.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_rembang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_rembang.setText("Rembang");
        b_rembang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rembangActionPerformed(evt);
            }
        });

        b_pati.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_pati.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_pati.setText("pati");
        b_pati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_patiActionPerformed(evt);
            }
        });

        b_blora.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_blora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_blora.setText("Blora");
        b_blora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bloraActionPerformed(evt);
            }
        });

        b_grobogan.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_grobogan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_grobogan.setText("Grobogan");
        b_grobogan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_groboganActionPerformed(evt);
            }
        });

        b_sragen.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_sragen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_sragen.setText("Sragen");
        b_sragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sragenActionPerformed(evt);
            }
        });

        b_sukoharjo.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_sukoharjo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_sukoharjo.setText("Sukoharjo");
        b_sukoharjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sukoharjoActionPerformed(evt);
            }
        });

        b_karanganyar.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_karanganyar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_karanganyar.setText("Karanganyar");
        b_karanganyar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_karanganyarActionPerformed(evt);
            }
        });

        b_wonogiri.setBackground(UColors.BRIGHT_ORANGE.toColor());
        b_wonogiri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_wonogiri.setText("Wonogiri");
        b_wonogiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_wonogiriActionPerformed(evt);
            }
        });

        LAYERED_PANE.setLayer(PETA_UTAMA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LAYERED_PANE.setLayer(b_brebes, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_tegal, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_cilacap, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_banyumas, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_purbalingga, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_pemalang, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_pekalongan, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_kebumen, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_purworejo, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_banjarnegara, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_kendal, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_batang, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_wonosobo, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_temanggung, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_magelang, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_semarang, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_demak, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_boyolali, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_klaten, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_kudus, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_jepara, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_rembang, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_pati, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_blora, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_grobogan, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_sragen, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_sukoharjo, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_karanganyar, javax.swing.JLayeredPane.DRAG_LAYER);
        LAYERED_PANE.setLayer(b_wonogiri, javax.swing.JLayeredPane.DRAG_LAYER);

        javax.swing.GroupLayout LAYERED_PANELayout = new javax.swing.GroupLayout(LAYERED_PANE);
        LAYERED_PANE.setLayout(LAYERED_PANELayout);
        LAYERED_PANELayout.setHorizontalGroup(
            LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_pati)
                .addGap(61, 61, 61)
                .addComponent(b_rembang)
                .addGap(44, 44, 44))
            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(b_purbalingga)
                        .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(b_temanggung)
                                .addGap(10, 10, 10)
                                .addComponent(b_semarang))
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(b_wonosobo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_sragen))))
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(b_cilacap)
                                .addGap(200, 200, 200)
                                .addComponent(b_banjarnegara)
                                .addGap(233, 233, 233)
                                .addComponent(b_boyolali))
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(b_kebumen)
                                .addGap(30, 30, 30)
                                .addComponent(b_purworejo)
                                .addGap(121, 121, 121)
                                .addComponent(b_klaten)
                                .addGap(3, 3, 3)
                                .addComponent(b_sukoharjo)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addGap(213, 213, 213))
            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(b_brebes)
                .addGap(68, 68, 68)
                .addComponent(b_pemalang)
                .addGap(93, 93, 93)
                .addComponent(b_batang)
                .addGap(32, 32, 32)
                .addComponent(b_kendal)
                .addGap(70, 70, 70)
                .addComponent(b_demak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addComponent(b_grobogan)
                        .addGap(79, 79, 79)
                        .addComponent(b_blora))
                    .addComponent(b_kudus))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addComponent(b_tegal)
                        .addGap(83, 83, 83)
                        .addComponent(b_pekalongan))
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addComponent(b_banyumas)
                        .addGap(267, 267, 267)
                        .addComponent(b_magelang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_karanganyar)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                        .addComponent(b_wonogiri)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                        .addComponent(b_jepara)
                        .addGap(274, 274, 274))))
            .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LAYERED_PANELayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PETA_UTAMA)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        LAYERED_PANELayout.setVerticalGroup(
            LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_pemalang)
                                    .addComponent(b_brebes))
                                .addGap(18, 18, 18))
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(b_jepara)
                                .addGap(111, 111, 111)
                                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b_demak)
                                    .addComponent(b_batang))
                                .addGap(23, 23, 23)))
                        .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_tegal)
                            .addComponent(b_pekalongan))
                        .addGap(19, 19, 19)
                        .addComponent(b_purbalingga)
                        .addGap(7, 7, 7)
                        .addComponent(b_cilacap)
                        .addGap(22, 22, 22))
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addComponent(b_kendal)
                                .addGap(50, 50, 50)
                                .addComponent(b_temanggung)
                                .addGap(19, 19, 19)
                                .addComponent(b_wonosobo))
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addComponent(b_semarang)
                                .addGap(46, 46, 46)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_banjarnegara)))
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addComponent(b_banyumas)
                        .addGap(39, 39, 39)
                        .addComponent(b_kebumen)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(b_magelang)
                        .addGap(42, 42, 42)
                        .addComponent(b_purworejo)
                        .addGap(141, 141, 141))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LAYERED_PANELayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(b_pati)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAYERED_PANELayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_rembang)
                                .addGap(6, 6, 6)))
                        .addComponent(b_kudus)
                        .addGap(49, 49, 49)
                        .addComponent(b_grobogan))
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(b_blora)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(53, 53, 53)
                .addComponent(b_sragen)
                .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(b_boyolali)
                        .addGap(66, 66, 66)
                        .addComponent(b_klaten))
                    .addGroup(LAYERED_PANELayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(b_karanganyar)
                        .addGap(28, 28, 28)
                        .addComponent(b_sukoharjo)))
                .addGap(43, 43, 43)
                .addComponent(b_wonogiri)
                .addGap(81, 81, 81))
            .addGroup(LAYERED_PANELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LAYERED_PANELayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(PETA_UTAMA)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYERED_PANE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LAYERED_PANE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_brebesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_brebesActionPerformed
        checkSet("BREBES");
    }//GEN-LAST:event_b_brebesActionPerformed

    private void b_tegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tegalActionPerformed
        checkSet("TEGAL");
    }//GEN-LAST:event_b_tegalActionPerformed

    private void b_cilacapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cilacapActionPerformed
        checkSet("CILACAP");
    }//GEN-LAST:event_b_cilacapActionPerformed

    private void b_banyumasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_banyumasActionPerformed
        checkSet("BANYUMAS");
    }//GEN-LAST:event_b_banyumasActionPerformed

    private void b_pemalangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pemalangActionPerformed
        checkSet("PEMALANG");
    }//GEN-LAST:event_b_pemalangActionPerformed

    private void b_pekalonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pekalonganActionPerformed
        checkSet("PEKALONGAN");
    }//GEN-LAST:event_b_pekalonganActionPerformed

    private void b_kebumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kebumenActionPerformed
        checkSet("KEBUMEN");
    }//GEN-LAST:event_b_kebumenActionPerformed

    private void b_kendalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kendalActionPerformed
        checkSet("KENDAL");
    }//GEN-LAST:event_b_kendalActionPerformed

    private void b_banjarnegaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_banjarnegaraActionPerformed
        checkSet("BANJARNEGARA");
    }//GEN-LAST:event_b_banjarnegaraActionPerformed

    private void b_wonosoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_wonosoboActionPerformed
        checkSet("WONOSOBO");
    }//GEN-LAST:event_b_wonosoboActionPerformed

    private void b_temanggungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_temanggungActionPerformed
        checkSet("TEMANGGUNG");
    }//GEN-LAST:event_b_temanggungActionPerformed

    private void b_magelangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_magelangActionPerformed
        checkSet("MAGELANG");
    }//GEN-LAST:event_b_magelangActionPerformed

    private void b_semarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_semarangActionPerformed
        checkSet("SEMARANG");
    }//GEN-LAST:event_b_semarangActionPerformed

    private void b_demakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_demakActionPerformed
        checkSet("DEMAK");
    }//GEN-LAST:event_b_demakActionPerformed

    private void b_boyolaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boyolaliActionPerformed
        checkSet("BOYOLALI");
    }//GEN-LAST:event_b_boyolaliActionPerformed

    private void b_klatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_klatenActionPerformed
        checkSet("KLATEN");
    }//GEN-LAST:event_b_klatenActionPerformed

    private void b_kudusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kudusActionPerformed
        checkSet("KUDUS");
    }//GEN-LAST:event_b_kudusActionPerformed

    private void b_jeparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_jeparaActionPerformed
        checkSet("JEPARA");
    }//GEN-LAST:event_b_jeparaActionPerformed

    private void b_rembangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rembangActionPerformed
        checkSet("REMBANG");
    }//GEN-LAST:event_b_rembangActionPerformed

    private void b_patiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_patiActionPerformed
        checkSet("PATI");
    }//GEN-LAST:event_b_patiActionPerformed

    private void b_bloraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bloraActionPerformed
        checkSet("BLORA");
    }//GEN-LAST:event_b_bloraActionPerformed

    private void b_groboganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_groboganActionPerformed
        checkSet("GROBOGAN");
    }//GEN-LAST:event_b_groboganActionPerformed

    private void b_sragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sragenActionPerformed
        checkSet("SRAGEN");
    }//GEN-LAST:event_b_sragenActionPerformed

    private void b_sukoharjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sukoharjoActionPerformed
        checkSet("SUKOHARJO");
    }//GEN-LAST:event_b_sukoharjoActionPerformed

    private void b_karanganyarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_karanganyarActionPerformed
        checkSet("KARANGANYAR");
    }//GEN-LAST:event_b_karanganyarActionPerformed

    private void b_wonogiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_wonogiriActionPerformed
        checkSet("WONOGIRI");
    }//GEN-LAST:event_b_wonogiriActionPerformed

    private void b_purbalinggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_purbalinggaActionPerformed
        checkSet("PURBALINGGA");
    }//GEN-LAST:event_b_purbalinggaActionPerformed

    private void b_batangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_batangActionPerformed
        checkSet("BATANG");
    }//GEN-LAST:event_b_batangActionPerformed

    private void b_purworejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_purworejoActionPerformed
        checkSet("PURWOREJO");
    }//GEN-LAST:event_b_purworejoActionPerformed

    /**
     * Melakukan pengecekan terhadap nama kota yang diberikan. Pengecekan dilakukan dengan cara membandingkan nama kota
     * yang diberikan dengan nama kota asal dan tujuan pada {@link MainFrame}. Jika nama kota yang diberikan sama dengan
     * nama kota asal atau tujuan, maka akan menampilkan dialog informasi. Jika tidak ada entri yang sama pada waktu
     * tersebut, maka akan diset kota tujuannya dengan nama label yang diberikan.
     * */
    private void checkSet(String cityName) {
        if (mainFrame.isCurrentOrigin(cityName)) {
            JOptionPane.showMessageDialog(
                this,
                "Kota sudah dipilih sebagai asal!",
                "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
        } else if (mainFrame.isCurrentDestination(cityName)) {
            JOptionPane.showMessageDialog(
                this,
                "Kota sudah dipilih sebagai tujuan!",
                "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            mainFrame.setCurrentDestination(cityName);
        }
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LAYERED_PANE;
    private javax.swing.JLabel PETA_UTAMA;
    private javax.swing.JButton b_banjarnegara;
    private javax.swing.JButton b_banyumas;
    private javax.swing.JButton b_batang;
    private javax.swing.JButton b_blora;
    private javax.swing.JButton b_boyolali;
    private javax.swing.JButton b_brebes;
    private javax.swing.JButton b_cilacap;
    private javax.swing.JButton b_demak;
    private javax.swing.JButton b_grobogan;
    private javax.swing.JButton b_jepara;
    private javax.swing.JButton b_karanganyar;
    private javax.swing.JButton b_kebumen;
    private javax.swing.JButton b_kendal;
    private javax.swing.JButton b_klaten;
    private javax.swing.JButton b_kudus;
    private javax.swing.JButton b_magelang;
    private javax.swing.JButton b_pati;
    private javax.swing.JButton b_pekalongan;
    private javax.swing.JButton b_pemalang;
    private javax.swing.JButton b_purbalingga;
    private javax.swing.JButton b_purworejo;
    private javax.swing.JButton b_rembang;
    private javax.swing.JButton b_semarang;
    private javax.swing.JButton b_sragen;
    private javax.swing.JButton b_sukoharjo;
    private javax.swing.JButton b_tegal;
    private javax.swing.JButton b_temanggung;
    private javax.swing.JButton b_wonogiri;
    private javax.swing.JButton b_wonosobo;
    // End of variables declaration//GEN-END:variables
}
